sudo: required
services:
    - docker

before_install:
    - docker build -t sambhaba/complexreactapp -f ./client/Dockerfile.dev ./client 

script:
    - docker run -e CI=true sambhaba/complexreactapp npm  test -- --coverage

after_success:
   - docker build -t sambhaba/multi-client ./client 
   - docker build -t sambhaba/multi-server ./server
   - docker build -t sambhaba/multi-worker ./worker
   - docker build -t sambhaba/multi-nginx  ./nginx

   #login into docker hub       
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

   #puching to docker hub
   - docker push sambhaba/multi-client
   - docker push sambhaba/multi-server
   - docker push sambhaba/multi-worker
   - docker push sambhaba/multi-nginx

  
   deploy:    
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-141043694641
    bucket_path: docker-multi     
    on:
       branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
            secure: $AWS_SECRET_KEY
        
